name: VT034 - Sample landscape setup
# This file creates an account structure for a company with three
# business units (HR, IT, SALES) and aubaccounts for dev, test and prod

on:
  workflow_dispatch:

jobs:
    integration-test:
        runs-on: ubuntu-latest
        container:
          image: ghcr.io/sap-samples/btp-setup-automator-dev:dev
          options: --user root
        env: 
            BTPSA_PARAM_MYEMAIL: ${{ secrets.BTPSA_PARAM_MYEMAIL }}
            BTPSA_PARAM_GLOBALACCOUNT: ${{ secrets.BTPSA_PARAM_GLOBALACCOUNT }}
            BTPSA_PARAM_MYPASSWORD: ${{ secrets.BTPSA_PARAM_MYPASSWORD }}
        steps:
            - name: 'Setup landscape for HR DEV'
              if: ${{ always() }}
              working-directory: /home/user
              shell: bash
              run: ./btpsa -parameterfile 'https://raw.githubusercontent.com/rui1610/dsag_tt_2023/main/vt034_landscape/hr/dev/parameters.json'
